[package]
name = "harbour-whisperfish"
version = "0.6.0-alpha.1"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"
build = "build.rs"
license = "AGPL-3.0-or-later"
description = "Private messaging using Signal for SailfishOS."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0-alpha.3"
awc = { version = "2.0.0-alpha.2", features=["rustls"] }
actix-codec = { version = "0.2.0" }
rustls = "0.17"
aes = "0.4.0"
block-modes = "0.4.0"
hmac = "0.8.0"
sha2 = "0.9.0"
pbkdf2 = { version = "0.4.0", default-features = false }
sha-1 = "0.9.0"
actix-threadpool = "0.3"
actix-rt = "1.0.0"
actix_derive = "0.5"
chrono = "0.4"
tokio = {version="0.2", features=["io-driver", "time", "stream"]}
mio = "0.6"
futures = "0.3"
pin-utils = "0.1"
qmetaobject = { version = "0.1.4", git = "https://gitlab.com/rubdos/qmetaobject-sfos-rs", branch = "sailfishos" }
cstr = "0.1.0"
cpp = "0.5"
dirs = "2.0"
failure = "0.1.6"
thiserror = "1"
libsignal-protocol = { git = "https://github.com/Michael-F-Bryan/libsignal-protocol-rs" }
libsignal-service = { git = "https://github.com/Michael-F-Bryan/libsignal-service-rs", branch = "MessageReceiver" }
libsignal-service-actix = { git = "https://github.com/Michael-F-Bryan/libsignal-service-rs", branch = "MessageReceiver" }
log = "0.4.8"
env_logger = "0.7"
scrypt = { version = "0.3", default-features = false, features=["std"] }
hex="0.4"
phonenumber = "0.2.4"

diesel = { version = "1.4", features = ["sqlite", "chrono"] }
diesel_migrations = "1.4"
libsqlite3-sys = { version = "0.9", features = ["sqlcipher"] }

serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"

[build-dependencies]
cpp_build = "0.5"
failure = "0.1.6"
dotenv = "0.15"
regex = "1.3.9"

[dev-dependencies]
rstest = {version = "0.6.5", git = "https://github.com/la10736/rstest/", branch = "master"}

[package.metadata.rpm]
target_architecture = "armv7hl"

[package.metadata.rpm.cargo]
buildflags = ["--release"]
target = "armv7-unknown-linux-gnueabihf"

[package.metadata.rpm.targets]
harbour-whisperfish = { path = "/usr/bin/harbour-whisperfish" }

[package.metadata.rpm.files]
"../harbour-whisperfish.desktop" = { path = "/usr/share/applications/harbour-whisperfish.desktop" }
"../icons/86x86/harbour-whisperfish.png" = { path = "/usr/share/icons/hicolor/86x86/apps/harbour-whisperfish.png" }

"../qml/" = { path = "/usr/share/harbour-whisperfish/qml/" }
"../icons/" = { path = "/usr/share/harbour-whisperfish/icons/" }
"../translations/" = { path = "/usr/share/harbour-whisperfish/translations" }

[features]
sailfish = []
